employee_name = input("Enter employee's name: ")
employee_id = input("Enter employee's ID: ")
department = input("Enter department name: ")
salary = float(input("Enter employee's salary: "))
print("Employee Details:")
print("Name:", employee_name)
print("ID:", employee_id)
print("Department:", department)
print("Salary:", salary)   