student_name = input("Enter student's name: ")
roll_number = input("Enter student's roll number: ")
subject = input("Enter subject name: ")
marks = float(input("Enter marks obtained: "))
print("Student Details:")
print("Name:", student_name)
print("Roll Number:", roll_number)
print("Subject:", subject)
print("Marks:", marks)